# Source: https://github.com/actions/starter-workflows/blob/main/ci/go.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # Test golangci-lint for go-version define in go.mod
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe #v4.1.0
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc #v3.7.0
        with:
          version: latest
          only-new-issues: true

  # Test with EPUBCheck and send test coverage
  test-epubcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    # This needs to come after the checkout, which wipes the working directory
    - name: Download EPUBCheck
      run: |
        # Download the latest version of EPUBCheck
        wget $(curl -Ls -H "Accept: application/vnd.github.v3+json" 'https://api.github.com/repos/IDPF/epubcheck/releases?per_page=1' | jq '.[0].assets[0].browser_download_url' -r)
        unzip epubcheck-*.zip

    - name: Set up Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version-file: ./go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -coverprofile=profile.cov ./...

    - name: Send coverage
      uses: shogo82148/actions-goveralls@df920a6a2468668dfcf71a0b43817f89eaa5ea04 # v1.7.0
      with:
        path-to-profile: profile.cov

  # Test Mac and Windows with the latest version of Go
  test-mac-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

    - name: Set up Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version-file: ./go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
